name: 🐛 Poetry-Import-Plugin Bug
description: Report a bug or unexpected behavior in Poetry-import-plUgin
labels: [bug, unconfirmed]

body:
  - type: markdown
    attributes:
      value: Thank you for contributing to poetry-import-plugin! ✊

  - type: checkboxes
    id: checks
    attributes:
      label: Initial Checks
      description: Just making sure you're really using Poetry-import-plugin
      options:
        - label: I confirm that I'm using Poetry-import-plugin
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Please explain what you're seeing and what you would expect to see.
        Provide as much detail as possible for quicker problem understanding and resolution. 🙏
    validations:
      required: true

  - type: textarea
    id: example
    attributes:
      label: Example Code
      description: >
        If applicable, please add a self-contained,
        [minimal, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
        demonstrating the bug.
      placeholder: |
        poetry import-req ...
      render: Python

  - type: textarea
    id: version
    attributes:
      label: Python, verion of poetry-import-plugin. your applications settings & OS Version
      description: |
        Please provide the following infos
        - Which versions of Python, Poetry, Poetry-Import-Plugin, and OS are you using?
        - What is your application settings?

        Run the following command and copy the output:

        For `poetry` users:
          ```bash
          poetry show poetry-import-plugin
          ```

      render: Text
    validations:
      required: true

  - type: checkboxes
    id: type_of_issue
    attributes:
      label: Affected Components
      description: "Please make sure you provided the following information"
      options:
        - label: Poetry version
        - label: "Operating system is provided"
        - label: Provide IDE screenshot if it's possible
