name: main

on:
  push:
    branches:
      - main
    paths:
      - poetry_import/**/*
      - poetry.lock
      - .github/**/*

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
  run-pytests:
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
        poetry-version: ["1.3", "1.4", "1.5"]
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: prepare pipx, poetry and dependencies
        run: |
          python -m pip install --user pipx
          python -m pipx ensurepath
          pipx install poetry=="${poetry_version}"
          poetry install --without dev
          poetry show
        env:
          poetry_version: ${{ matrix.poetry-version }}
      - name: run tests
        run: |
          poetry run python -m pytest -k unittests --cov -vvvv
